### ISSUE TITLE
Different configurations for different files

### ISSUE THREAD

**Issue by jesucarr** [javascript-obfuscator/react-native-obfuscating-transformer#3]
Is there a way to set different obfuscatorOptions for different files?

**Comment by ds300** [comment]
Hi! :wave: Sorry for the delay in responding. Unfortunately there is no way to configure the obfuscator on a per-file basis at the moment.

**Comment by jesucarr** [comment]
I managed to create 2 transformers and load conditionally so I guess it's not needed

**Comment by satheeshwaran** [comment]
@jesucarr I am trying to create two transformers for different file types, how did you handle it?

**Comment by jesucarr** [comment]
@satheeshwaran using `module.exports.transform` with an `if` inside
