### ISSUE TITLE
Transform file error

### ISSUE THREAD

**Issue by rohitmodi12** [javascript-obfuscator/react-native-obfuscating-transformer#31]
I am trying to use "react-native-obfuscating-transformer" npm but I am facing an error:

"TypeError: Cannot read property 'transformFile' of undefined"
Anyone have solution? Please let me know.

**Comment by alexandrejsx** [comment]
See https://github.com/javascript-obfuscator/react-native-obfuscating-transformer/issues/16#issuecomment-628481855

**Comment by rohitmodi12** [comment]
@alexandrejsx 
Thanks working.

**Comment by rohitmodi12** [comment]
Hello @alexandrejsx 
Do we need to run any command before create build("./gradlew assemblerelease")?
Because with and without obfuscating, I am getting same code means it is not obfuscating.

**Comment by rohitmodi12** [comment]
I need to obfuscate one selected file instead of src folder.

**Comment by Coder108** [comment]
@rohitmodi12 Hello, Are you making it to obfuscate the js code of the react-native project?
