### ISSUE TITLE
"enableInDevelopment: false" option doesn't seem to be working, typescript builds failing even on on dev mode

### ISSUE THREAD

**Issue by TowhidKashem** [javascript-obfuscator/react-native-obfuscating-transformer#65]
I run the following command as a pre commit git hook to confirm that there aren't any TypeScript errors in the project:

`tsc --project tsconfig.json`

but after setting up `react-native-obfuscating-transformer` (which is working great for the intended purpose) this command continues to fail with lots of errors such as these:

<img width="1792" alt="Screen Shot 2022-08-14 at 11 01 54 AM" src="https://user-images.githubusercontent.com/1139927/184527978-37f9b72b-9fb1-497e-ae57-e041948b045a.png">

Which makes me think that the obsfucator is running in dev mode even though the default value of `enableInDevelopment` is supposed to be false and I even explicitly set it to false. Anyone else experiencing this issue?

**Comment by JacobDel** [comment]
How did you fix this issue? Because after enabling this variable you probably encountered new TypeScript errors as well?

**Comment by TowhidKashem** [comment]
> How did you fix this issue? Because after enabling this variable you probably encountered new TypeScript errors as well?

I don't remember what came of this just that I ended up using this other obfuscator which worked much better:

https://github.com/whoami-shubham/obfuscator-io-metro-plugin
